### ISSUE TITLE
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})

### ISSUE THREAD

**Issue by kyegomez** [google-gemini/generative-ai-python#117]
### Description of the bug:

package verison: 0.3.1

```
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 65, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-13T23:10:10.374012-08:00", grpc_status:14, grpc_message:"Getting metadata from plugin failed with error: (\'invalid_grant: Bad Request\', {\'error\': \'invalid_grant\', \'error_description\': \'Bad Request\'})"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/defalt/Desktop/Athena/research/swarms/gemini.py", line 23, in <module>
    response = model.generate_content("The opposite of hot is")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/generativeai/generative_models.py", line 243, in generate_content
    response = self._client.generate_content(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 566, in generate_content
    response = rpc(
               ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/google/api_core/retry.py", line 207, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by huqin-RM** [comment]
![Uploading 20231214-165300.jpg…]()

**Comment by huqin-RM** [comment]
![20231214-165300](https://github.com/google/generative-ai-python/assets/72855121/649239a7-5dd9-4da4-b952-0b427ddadf4b)

**Comment by HaoyuanShi** [comment]
The same problem encountered by me

**Comment by huqin-RM** [comment]
> 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问

You can bypass GRPC and use rest:

genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

**Comment by kyegomez** [comment]
@huqin-RM thanks that worked, I'm integrating it into the Swarms framework that enables developers to Build, Deploy, and Scale Reliable Autonomous Agents!

https://www.swarms.world/

And, here is the docs for our abstracted away Gemini wrapper:
https://swarms.apac.ai/en/latest/swarms/models/gemini/

**Comment by sleeper1023** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:您可以绕过 GRPC 并使用 rest：
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')genai.configure（api_key=GOOGLE_API_KEY，transport='休息'）

thanks,^_^

**Comment by sleeper1023** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

This works, thank you very much

**Comment by HaoyuanShi** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

It really works.

**Comment by RickYangzz** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

Thank you, it's worked. And I still want to know why you know this way can work?

**Comment by huqin-RM** [comment]
> > > 我也遇到了这个问题 GRPC Return 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s 超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知： ipv4：172.217.160.74：443：无法连接到远程主机：FD关闭。IP无法访问
> > 
> > 
> > 您可以绕过 GRPC 并使用休息：
> > genai.configure(api_key=GOOGLE_API_KEY,transport=“休息”)
> 
> 谢谢，已经成功了。我还想知道为什么你知道这种方法可行？
Because the example about REST in the official manual is to directly use curl to make API requests. [I](https://ai.google.dev/tutorials/rest_quickstart) can run the command line directly from my terminal, so I'm sure it's not a network problem. 
Looking further at the pythonsdk source code, there are the following comments:
![20231218-184550](https://github.com/google/generative-ai-python/assets/72855121/b5843be5-675f-491f-9d16-b596458dc602)

**Comment by RickYangzz** [comment]
> > > > 我也遇到了这个问题 GRPC Return 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s 超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知： ipv4：172.217.160.74：443：无法连接到远程主机：FD关闭。IP无法访问
> > > 
> > > 
> > > 您可以绕过 GRPC 并使用休息：
> > > genai.configure(api_key=GOOGLE_API_KEY,transport=“休息”)
> > 
> > 
> > 谢谢，已经成功了。我还想知道为什么你知道这种方法可行？
> > Because the example about REST in the official manual is to directly use curl to make API requests. [I](https://ai.google.dev/tutorials/rest_quickstart) can run the command line directly from my terminal, so I'm sure it's not a network problem.
> > Looking further at the pythonsdk source code, there are the following comments:
> > ![20231218-184550](https://private-user-images.githubusercontent.com/72855121/291255296-b5843be5-675f-491f-9d16-b596458dc602.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjU0NTQsIm5iZiI6MTcwMjk2NTE1NCwicGF0aCI6Ii83Mjg1NTEyMS8yOTEyNTUyOTYtYjU4NDNiZTUtNjc1Zi00OTFmLTlkMTYtYjU5NjQ1OGRjNjAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA1NTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2M1NmE3ZjYxYTZjNGE1YzJkMzM4MWVjMzIyOWU0MWE3OTcyYTllNDFkYzIwMzU0Nzc1YWYwY2IzNDA0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pTDrLvdCJUFYlJahBUuXidokcHJSt8-3LLDt7ChgHjY)

Thank you. You have a clear way to solve problem.

**Comment by cgnannan** [comment]
Thanks a lot,it works.

**Comment by cgnannan** [comment]
> > > > 我也遇到了这个问题 GRPC Return 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s 超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知： ipv4：172.217.160.74：443：无法连接到远程主机：FD关闭。IP无法访问
> 
> > > 
> 
> > > 
> 
> > > 您可以绕过 GRPC 并使用休息：
> 
> > > genai.configure(api_key=GOOGLE_API_KEY,transport=“休息”)
> 
> > 
> 
> > 谢谢，已经成功了。我还想知道为什么你知道这种方法可行？
> 
> Because the example about REST in the official manual is to directly use curl to make API requests. [I](https://ai.google.dev/tutorials/rest_quickstart) can run the command line directly from my terminal, so I'm sure it's not a network problem. 
> 
> Looking further at the pythonsdk source code, there are the following comments:
> 
> ![20231218-184550](https://github.com/google/generative-ai-python/assets/72855121/b5843be5-675f-491f-9d16-b596458dc602)
> 
> 
> 
> 

Thanks a lot.It works and solves a problem that has been bothering me for three weeks.

**Comment by OhMyDamnCode** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

I/m having this error msg now:

**Comment by bezir** [comment]
In my case the problem was docker, I reinstalled the docker to fix the problem (though I acknowledge there might be a better solution)

**Comment by HrushikeshPawar** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

The problem with GRPC is still same even after two months.
But this `transport='rest'` does solve the problem. Thanks

Hoping that the problem with GRPC will be solved soon. Facing same issue with `TextGeneration` on VertexAI as well.

**Comment by Hoper-J** [comment]
This solved my issue😄. You should replace `port` with your proxy server's port number:

```python
import os

os.environ['http_proxy'] = 'http://127.0.0.1:port'
os.environ['https_proxy'] = 'http://127.0.0.1:port'
os.environ['all_proxy'] = 'socks5://127.0.0.1:port'
```

**Comment by observerkei** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')


Thanks for sharing! The problem that has bothered me for a long time does not seem to be found in the official document 😂

**Comment by gyp3085000** [comment]
genai.configure（api_key=GOOGLE_API_KEY，transport='rest'）
The problem can be solved, but the streaming Q&A output will fail.

**Comment by MizukiRin** [comment]
> > 我也遇到了这个问题 GRPC 返回 503，但我的错误是 google.api_core.exceptions.RetryError: Deadline of 60.0s超过调用目标函数时，最后一个异常：503 无法连接到所有地址；最后一个错误：未知：ipv4：172.217.160.74：443：无法连接到远程主机：FD 关闭。 IP无法访问
> 
> You can bypass GRPC and use rest:
> 
> genai.configure(api_key=GOOGLE_API_KEY,transport='rest')

Thanks! It really works.

**Comment by markmcd** [comment]
Lots happened in this thread - is there anything left we can help with? If not, we'll close this one.

**Comment by WiKiBIRD** [comment]
> ,transport='rest'

It works, thank you.

**Comment by Hcl192088** [comment]
Sometimes it work some times dont. Is there another solution to this problem?
