### ISSUE TITLE
Async embed_content

### ISSUE THREAD

**Issue by markmcd** [google-gemini/generative-ai-python#125]
### Description of the feature request:

GLAPI supports `embed_content` through the async client, so we should support it through the SDK too.

### What problem are you trying to solve with this feature?

Embedding content, asynchronously.

**Comment by MarkDaoust** [comment]
@mayureshagashe2105 has volonteered to work on this.

**Comment by MarkDaoust** [comment]
Fixed: https://github.com/google-gemini/generative-ai-python/pull/189
