### ISSUE TITLE
ModuleNotFoundError - GoogleAI, Pyinstaller

### ISSUE THREAD

**Issue by NumerusXXL** [google-gemini/generative-ai-python#152]
### Description of the bug:

I am building a simple app. When I try to make the .py to exe using no matter which tool Pyinstaller ,py2exe. Nothing works. It makes an exe for me, but it always says module google not found. I also tried it with VERY simple code, using only the google library, but same issue:

```
import time

import google.generativeai as genai
genai.configure(api_key="///")
gemini_model = genai.GenerativeModel('gemini-pro')
prompt = input()
completion = gemini_model.generate_content(
        prompt,
        generation_config=genai.types.GenerationConfig(

            temperature=0.3)
    )
response = completion.text
print(response)
```

I use the `pyinstaller --onefile main.py`
I installed the library and it successfully works in pycharm as a .py
Here is the error:
![photo_2023-12-23_16-34-54](https://github.com/google/generative-ai-python/assets/117753548/3f532ea7-5348-4dab-ae92-3eba61cf8eae)

### Actual vs expected behavior:

It should be included. I also Tried to inculde the library extra, but it just doesnt work. Tried it also on different machines, py versions ans so on...

### Any other information you'd like to share?

Using Python 3.11.2

**Comment by MarkDaoust** [comment]
Hi, IDK about these tools, but remember that `google` is a namespace package. It may require a different setup compared to regular packages. Check for "namespace packages" in their documentation.
