### ISSUE TITLE
Function Calling 

### ISSUE THREAD

**Issue by EMPERORAYUSH** [google-gemini/generative-ai-python#155]
### Description of the feature request:

A curl wrapper for function calling for the existing google-generativeai SDK for python. It would be a very good addition as people can continue using this library even for function calling feature. It's already available in api and can be used in vertex. It would be a crucial addition to compete to openai as this library api usage is free too.

**Comment by liqul** [comment]
Exactly, support this feature!

**Comment by ymodak** [comment]
This feature is now part of v1beta version of the Gemini API.
See [function_calling](https://ai.google.dev/docs/function_calling). Thanks!

**Comment by MarkDaoust** [comment]
https://github.com/google-gemini/cookbook/blob/main/quickstarts/rest/Function_calling_REST.ipynb

https://github.com/google-gemini/cookbook/blob/main/quickstarts/Function_calling.ipynb
