### ISSUE TITLE
Support multimodal embeddings

### ISSUE THREAD

**Issue by stevenaldinger** [google-gemini/generative-ai-python#157]
### Description of the feature request:

Vertex AI has a `multimodal` embeddings model, this only supports text embeddings.

### What problem are you trying to solve with this feature?

I need multimodal embeddings.

### Any other information you'd like to share?

I don't understand the difference between this API and Vertex AI.

I moved to this after starting with Vertex thinking this was the new stuff, but now I'm just confused.

**Comment by MarkDaoust** [comment]
This repoistory just manages the SDK for the API, multimodal embeddings would be nice, and the API is setup to handle that, but we don't have more deatils about when/if it will be added to the API.

Vertex has more stuff, including a gemini API. Here we only have the gemini api, so people can avoid the added complexity of vertex if that works for them.
