### ISSUE TITLE
[Feature] Add Support on Log Probability Value from Returned Response of Gemini Models.

### ISSUE THREAD

**Issue by jacklanda** [google-gemini/generative-ai-python#238]
### Description of the feature request:

How about providing new support for retrieving the log probability of each predicted token by Google models like Gemini?

Something just like the same function illustrated in this OpenAI post: [User Logprobs](https://cookbook.openai.com/examples/using_logprobs).

### What problem are you trying to solve with this feature?

Getting the returned log prob of each generated token does help me (and other users maybe) to confirm the confidence of the model's prediction. Further, this feature can help users compute the perplexity of generated sentences to better understand the textual continuation quality.

**Comment by jacklanda** [comment]
Any thoughts about it?

**Comment by Brian-Ckwu** [comment]
I also think it would be extremely helpful if the API could provide the top-k log probabilities of each predicted token.

**Comment by krenova** [comment]
Really need this as I found Gemini to be hallucinating quite abit on a RAG application. 

Btw your title refers to `claude` and not gemini.
`[Feature] Add Support on Log Probability Value from Returned Response of Claude Models`

**Comment by jacklanda** [comment]
> Really need this as I found Gemini to be hallucinating quite abit on a RAG application.
> 
> Btw your title refers to `claude` and not gemini. `[Feature] Add Support on Log Probability Value from Returned Response of Claude Models`

Thanks for reminding 🤗

**Comment by simpleusername96** [comment]
Many hallucination detection approaches rely on log probability as a key feature. It's one of the most essential elements when building a serious product with a LLM.

**Comment by anwang427** [comment]
This would be extremely helpful!

**Comment by Said-Apollo** [comment]
As all others previously mentioned, it would be great to somehow get access to the logsprobs in a similar fashion as OpenAI does so with the models. Based on that we could then e.g. calculate the perplexity score and various other evaluation metrics.

**Comment by haugmarkus** [comment]
Yep, this would make it possible to use gemini in production

**Comment by waveworks-ai** [comment]
+1 - useful also for classification tasks.

**Comment by lavanyanemani96** [comment]
+1

**Comment by luna-b20** [comment]
+1 it is critical. Chatgpt and other major models are now all supporting this feature.
please help!

**Comment by michaelgfeldman** [comment]
> +1 it is critical. Chatgpt and other major models are now all supporting this feature. please help!

Can you please specify what major models support this feature? Because I'm also in search for the alternatives. Now I don't see any other players supporting this except from OpenAI. No Anthropic, No Mistral...

**Comment by MarkDaoust** [comment]
b/361194489

**Comment by MFajcik** [comment]
> I also think it would be extremely helpful if the API could provide the top-k log probabilities of each predicted token.

Yes, this would allow evaluating Gemini with threshold-free evaluation metrics. That would be excellent.

**Comment by MarkDaoust** [comment]
Google's Vertex-AI Just launched this, hopefully that means it's coming soon here.

**Comment by michaelgfeldman** [comment]
> Google's Vertex-AI Just launched this, hopefully that means it's coming soon here, but I don't have a timeline.

can you share a link?

**Comment by haugmarkus** [comment]
> > Google's Vertex-AI Just launched this, hopefully that means it's coming soon here, but I don't have a timeline.
> 
> can you share a link?

They have added a field 'avgLogprobs' to the response documentation in https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#nodejs but I am unable to get a response with such field.

**Comment by MarkDaoust** [comment]
Yeah, this API is related, but separate from vertex. Hopefully this API will catch up soon.

**Comment by MarkDaoust** [comment]
This is fixed in the latest version: 

code: https://github.com/google-gemini/generative-ai-python/pull/561
tutorial: https://github.com/google-gemini/cookbook/blob/main/quickstarts/New_in_002.ipynb

**Comment by FraPochetti** [comment]
Just to make sure I get this right. The logprobs are averaged for the entire output, correct?
No logprob at token level?

**Comment by jacklanda** [comment]
> Just to make sure I get this right. The logprobs are averaged for the entire output, correct? No logprob at token level?

I recommend you open another issue to discuss this question =)

**Comment by FraPochetti** [comment]
Created a convo [here](https://discuss.ai.google.dev/t/get-logprobs-at-token-level/54418?u=francesco_pochetti) actually :)

**Comment by miaojingang** [comment]
The feature is available in only `gemini-2.0-flash-lite` and `gemini-1.5-flash` per https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference.

Would it be possible to extend to 1.5-pro and 2.0 models?

**Comment by chancharikmitra** [comment]
So there's some ambiguity in how this is being handled. To my knowledge, there was full support for logprobs just a few short months ago on Gemini's `generativeai` version of the api. But now, there is also a version called `genai`, which is different. If you actually print the attributes of the GenerationConfig class, you get the following:

`['__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'candidate_count', 'frequency_penalty', 'max_output_tokens', 'presence_penalty', 'response_mime_type', 'response_schema', 'stop_sequences', 'temperature', 'top_k', 'top_p']`

No `response_logprobs` or `responseLogprobs`. @miaojingang, can you share how you are getting the log prob feature even from the models you listed? Versions and example code of what you are doing would be appreciated as it's challenging to keep track of which version of the Gemini api this applies to.

**Comment by miaojingang** [comment]
Thanks @chancharikmitra for the detailed notes. I'm new to all those different implementation and find it confusing.

I saw the `generativeai` example using the parameter was removed in https://github.com/google-gemini/cookbook/pull/309. I got an timeout error last time I tried it. A colleague got something working and I will ask.

**Comment by slverpla** [comment]
@miaojingang how did they make it work?

**Comment by wmpauli** [comment]
I was able to get this to work with 

```
GENERATION_CONFIG = {
    "max_output_tokens": 8192,
    "temperature": 0,
    "top_p": 0,
    "response_logprobs": True,
    "logprobs": 5,
}
```

, but only for `gemini-1.5-flash`.

according to the documentation, it currently only works for gemini-2.0-flash-lite-001 and gemini-1.5-flash:
https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference

**Comment by tranhoangnguyen03** [comment]
It stopped working for `gemini-2.0-flash-lite-001` and `gemini-1.5-flash` now

**Comment by victoraavila** [comment]
+1 here. I am also not getting the logprobs for the Preview models. I am using the `google.genai` module:

`{'error': {'code': 400, 'message': 'Logprobs is not enabled for models/gemini-2.5-pro-preview-03-25', 'status': 'INVALID_ARGUMENT'}}`

`{'error': {'code': 400, 'message': 'Logprobs is not enabled for models/gemini-2.5-flash-preview-04-17', 'status': 'INVALID_ARGUMENT'}}`

**Comment by Tahlor** [comment]
It works on Vertex, 1 request per day, resets 12am Pacific.

UPDATE: They removed the one per day restriction in June 2025.

**Comment by nok** [comment]
Hello, these models support `logprobs` in VertexAI (`genai.Client(vertexai=True, [...])`):

```
                       model  logprobs  avg_logprobs  num_logprobs
0             gemini-2.5-pro      True     -0.695182           134
1           gemini-2.5-flash      True     -3.460884            11
2       gemini-2.0-flash-001      True     -0.000990            12
3  gemini-2.0-flash-lite-001      True     -0.000257            12
```

Here is my small test script:

```python
from os import environ

import pandas as pd
from google import genai
from google.genai.types import GenerateContentConfig, GenerateContentResponse

PROJECT = environ.get("PROJECT")
LOCATION = environ.get("LOCATION")


def check_genai_models():
    for model_id in [
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "gemini-2.0-flash-001",
        "gemini-2.0-flash-lite-001",
    ]:
        try:
            client = genai.Client(
                vertexai=True,
                project=PROJECT,
                location=LOCATION,
            )
            response: GenerateContentResponse = client.models.generate_content(
                model=model_id,
                contents="What's the largest planet in our solar system?",
                config=GenerateContentConfig(response_logprobs=True, logprobs=1),
            )
        except Exception as e:
            print(f"Error with model {model_id}: {e}")
            continue
        else:
            print(f"Processing model: {model_id}")
            if response.candidates[0].avg_logprobs:
                avg_logprobs = response.candidates[0].avg_logprobs
                num_logprobs = len(response.candidates[0].logprobs_result.chosen_candidates)
                yield dict(
                    model=model_id,
                    logprobs=True,
                    avg_logprobs=avg_logprobs,
                    num_logprobs=num_logprobs,
                )
            else:
                yield dict(
                    model=model_id,
                    logprobs=False,
                    avg_logprobs=None,
                    num_logprobs=None,
                )


def main():
    results = pd.DataFrame.from_records(check_genai_models())
    print(results.head(10))


if __name__ == "__main__":
    main()

```

**Comment by nok** [comment]
Hello, these models support `logprobs` in VertexAI (`genai.Client(vertexai=True, [...])`):

```
                       model  logprobs  avg_logprobs  num_logprobs
0             gemini-2.5-pro      True     -0.695182           134
1           gemini-2.5-flash      True     -3.460884            11
2       gemini-2.0-flash-001      True     -0.000990            12
3  gemini-2.0-flash-lite-001      True     -0.000257            12
```

Here is my small test script:

```python
from os import environ

import pandas as pd
from google import genai
from google.genai.types import GenerateContentConfig, GenerateContentResponse

PROJECT = environ.get("PROJECT")
LOCATION = environ.get("LOCATION")


def check_genai_models():
    for model_id in [
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "gemini-2.0-flash-001",
        "gemini-2.0-flash-lite-001",
    ]:
        try:
            client = genai.Client(
                vertexai=True,
                project=PROJECT,
                location=LOCATION,
            )
            response: GenerateContentResponse = client.models.generate_content(
                model=model_id,
                contents="What's the largest planet in our solar system?",
                config=GenerateContentConfig(response_logprobs=True, logprobs=1),
            )
        except Exception as e:
            print(f"Error with model {model_id}: {e}")
            continue
        else:
            print(f"Processing model: {model_id}")
            if response.candidates[0].avg_logprobs:
                avg_logprobs = response.candidates[0].avg_logprobs
                num_logprobs = len(response.candidates[0].logprobs_result.chosen_candidates)
                yield dict(
                    model=model_id,
                    logprobs=True,
                    avg_logprobs=avg_logprobs,
                    num_logprobs=num_logprobs,
                )
            else:
                yield dict(
                    model=model_id,
                    logprobs=False,
                    avg_logprobs=None,
                    num_logprobs=None,
                )


def main():
    results = pd.DataFrame.from_records(check_genai_models())
    print(results.head(10))


if __name__ == "__main__":
    main()

```

**Comment by sayap** [comment]
Nice. It works great with VertexAI `generateContent` method, but I got this error with the `streamGenerateContent` method:
```
{"error":{"message":"Unable to submit request because the model does not support the response_logprobs parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview","status":"INVALID_ARGUMENT"}}
```
Tested with both `gemini-2.5-flash` and `gemini-2.5-pro`

**Comment by farris** [comment]
This is still an issue, it works when using vertex but not the `google-genai` developer API, this is undesirable behavior and would be great if addressed
