### ISSUE TITLE
No access to api key

### ISSUE THREAD

**Issue by wailla** [google-gemini/generative-ai-python#251]
### Description of the bug:

I am part of an EU region available for Google AI Studio and API Gemini and I am over 18 years old, but when I try to access the API link it takes me to the documentation site telling me in a note: If you have reached this page after trying to open Google AI Studio, it is possible that Google AI Studio is not available in your region or you do not meet the age requirements for access (18 and older).
How come I can't make a request for an API key?

### Actual vs expected behavior:

The site should take me to my account and give me an API key

**Comment by LindaLawton** [comment]
Access is not controlled by this library you should as questions like this over on [discuss](https://discuss.ai.google.dev/) or the discord channel.

you cant use the API from the EU either.

**Comment by MarkDaoust** [comment]
Yes, thanks @LindaLawton.

The API is only available in [some regions](https://ai.google.dev/gemini-api/docs/available-regions), I can't fix that with this python package.
