### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by renatofrota** [google-gemini/generative-ai-python#262]
### Description of the feature request:

I would like to ask for Python 3.8 support.

### What problem are you trying to solve with this feature?

I develop Amazon Alexa Skills and would love to add IA features to them, however the environment offered to host the skills has only Python 3.8. That's not just the case of it being hard to upgrade my skill to use Python 3.10, its impossible to do (AFAIK).

### Any other information you'd like to share?

I can see 2 PRs were opened to add support earlier (https://github.com/google/generative-ai-python/pull/101 and https://github.com/google/generative-ai-python/pull/199), one closed other open pending. Could you reconsider?

**Comment by jstmn** [comment]
seconding, i'm trying to use this with a simulator that only supports python 3.8

**Comment by jstmn** [comment]
update: I made a fork that's python3.8 compatible https://github.com/jstmn/generative-ai-python-3.8

**Comment by MarkDaoust** [comment]
@jstmn - Cool! 
Thanks for doing this, but Google's phased out 3.8 internally, so we'd prefer not to go back.
