### ISSUE TITLE
Empty response when the finish reason is MAX_TOKENS

### ISSUE THREAD

**Issue by UMuktesh** [google-gemini/generative-ai-python#280]
### Description of the bug:

When using max_output_tokens in generate_content to limit the output of the model, the following error is thrown when trying to access response.text, whereas its expected to get the output till MAX_TOKENS.
 
ValueError: The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

The actual response:
```
response:
GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({'candidates': [{'finish_reason': 2, 'index': 0, 'safety_ratings': [{'category': 9, 'probability': 1, 'blocked': False}, {'category': 8, 'probability': 1, 'blocked': False}, {'category': 7, 'probability': 1, 'blocked': False}, {'category': 10, 'probability': 1, 'blocked': False}], 'token_count': 0, 'grounding_attributions': []}]}),
)
```

This is the code snippet, taken from https://ai.google.dev/tutorials/python_quickstart#generation_configuration, which shows expected behaviour is to get upto 20 tokens then cut off due to MAX_TOKENS.

```
import google.generativeai as genai

genai.configure(api_key='***')
model = genai.GenerativeModel('gemini-pro')
response = model.generate_content(
    'Tell me a story about a magic backpack.',
    generation_config=genai.types.GenerationConfig(
        # Only one candidate for now.
        candidate_count=1,
        # stop_sequences=['x'],     # Commenting this part as sometimes it works due to 'x' being present in output and model cuts off before MAX_TOKENS is reached.
        max_output_tokens=20,
        temperature=1.0)
)

text = response.text

if response.candidates[0].finish_reason.name == "MAX_TOKENS":
    text += '...'

print(text)
```

### Actual vs expected behavior:

https://ai.google.dev/tutorials/python_quickstart#generation_configuration
Similar output as of here, not error when trying to access response.text, but to get the output of approx 20 tokens.

Works in AI Studio
![image](https://github.com/google/generative-ai-python/assets/63556122/de19fca1-67da-4db5-b2ca-38c0e2781c82)

### Any other information you'd like to share?

Package information
Name: google-generativeai                                                                                                                            
Version: 0.5.0

Streaming partially works, but the last chunk with MAX_TOKENS is still empty (Could be intended behaviour)

**Comment by singhniraj08** [comment]
@UMuktesh,

Thank you for reporting this issue. I am able to replicate this error. While setting `max_output_tokens` to `None`, we are getting response from the model, but changing `max_output_tokens` to integer value results in no output text from model. Ref: [gist](https://colab.research.google.com/gist/singhniraj08/33f4539e4dbeb517e65a0b6c4bfa4f5b/genai_maxoutputtokenerror_280.ipynb)
@MarkDaoust, This looks like a bug in SDK. Please have a look. Thank you!

**Comment by ClayGriifith** [comment]
Facing a similar issue and unclear on whether or not this is by-design, but I'm getting an empty 'text' response when finishReason is MAX_TOKENS. 

I'd expect at least a partial response, if not (ideally) a response that is actually within the token threshold assigned. Getting nothing at all is confusing. 

Can somebody clarify if this is intended behavior?

**Comment by NicolaDonelli** [comment]
Same as above.

**Comment by lgnashold** [comment]
Same as above.

**Comment by homer6** [comment]
I ran into this too and it was very hard to track down. The exception was very misleading.

**Comment by scissorstail** [comment]
"The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked."

**Comment by MarkDaoust** [comment]
This is fixed.

**Comment by Akshay0799** [comment]
Did anyone manage to find a reason for why this was happening? 
I am using Gemini 2.5-flash-preview and I still face this problem sometimes and I can't seem to understand why this happens at times. 
There's no response from the LLM, the number of output_tokens in the usage_metadata is 0 and stop_reason is 'MAX_TOKENS'

**Comment by approxit1** [comment]
Also experiencing this problem with Gemini 2.5-flash-preview

**Comment by dsaad68** [comment]
I have the similar problem.

**Comment by aictodev** [comment]
has this been fixed?

**Comment by MarkDaoust** [comment]
Yes. 

If you think you see it happening, you've probably got your `max_output_tokens` set too low and they're all being used up in thinking. 

Check `usage_metadata` in the response to see where your tokens went. 

You can set the `thinkng_config` to adjust settings: `generate_content(..., config={'thinking_config': {'return_thoughts': True, 'thinking_budget':0}})`

**Comment by aictodev** [comment]
thanks for the prompt response, very helpful!!
