### ISSUE TITLE
google.generativeai.types.generation_types.BlockedPromptException: prompt_feedback {   block_reason: OTHER }

### ISSUE THREAD

**Issue by xxl4** [google-gemini/generative-ai-python#305]
### Description of the bug:

This is our model config and when have a few image don't work fine.

![image](https://github.com/google-gemini/generative-ai-python/assets/34465153/4f5de1c4-13f8-4e3d-a3ba-2219f207646c)

response

![image](https://github.com/google-gemini/generative-ai-python/assets/34465153/e88c3fd7-5f00-4153-8233-aec65bb6af64)

but when i use the same the image and content on google ai platform will give more info.

Thank you.

**Comment by singhniraj08** [comment]
@xxl4,

There are some filters that can't be turn off, these all go into the "OTHER" finish reason. For example: one of the non-configurable filters is child safety, which is a legal requirement.

These filters are set at Gemini API and can't be configured from SDK. For issues related to Gemini, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key) and provide example prompts which can be sent to owners as an example of False Positive. Ref: Screenshot below. Thank you!

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by mm-khalil1** [comment]
I am receiving the same error, but with text generation.
My prompts are basically about asking the model to rate a video transcript according to couple of questions about credibility (aims, sources,  dates, etc). Each question along with the transcript is sent as a single prompt.

Anyone was able to avoid this error?
