### ISSUE TITLE
google needs prepaid contract and $3500 for BLOCK_NONE to work 

### ISSUE THREAD

**Issue by nekohacker591** [google-gemini/generative-ai-python#306]
### Description of the bug:

is this true 

### Actual vs expected behavior:

...

### Any other information you'd like to share?

i would like to know if the filter config is paywalled? as per my developer said

**Comment by nekohacker591** [comment]
this is for gemeni api

**Comment by singhniraj08** [comment]
@nekohacker591,

Thank you reporting this issue. 
This repository is for issues related to Python SDK. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. Thank you!

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
