### ISSUE TITLE
Gemini version 0.5.* generate_content doesn't provide usageMetadata if stream=True

### ISSUE THREAD

**Issue by Mersanko** [google-gemini/generative-ai-python#317]
### Description of the bug:

I believe this is related to [https://github.com/google/generative-ai-go/issues/97](https://github.com/google/generative-ai-go/issues/url)

### Actual vs expected behavior:

As far as I remember, it worked earlier this week. I tried all version 0.5.* but the same issue. The issue was fixed when I utilized version 0.4.0
<img width="672" alt="issue97" src="https://github.com/google-gemini/generative-ai-python/assets/60516646/9c02b601-1f14-4536-952a-5d9674bfbd2d">

**Comment by singhniraj08** [comment]
@Mersanko, I tried replicating the issue on our end and `model.generate_content` works with `stream=True` parameter. 
Ref: Screenshot below. Package version used: `google.generativeai==0.5.2`

Can you please share a colab gist with replicated issue so we can reproduce the issue on our end. Thank you.

![image](https://github.com/google-gemini/generative-ai-python/assets/110809167/e484613a-9dff-49d6-9c5b-d8af7b24d655)
