### ISSUE TITLE
stream=True returns all chunks at the same time [in Colab]

### ISSUE THREAD

**Issue by sykp241095** [google-gemini/generative-ai-python#329]
### Description of the bug:

I have read the docs here https://ai.google.dev/api/python/google/generativeai/GenerativeModel to learn that use `stream=True` could return chunks of response one by one, but when I was trying with the following simple code, it doesn't work, it return chunks, but it seems like to return all the chunks at the same time:

```python
import google.generativeai as genai


genai.configure(api_key='....')
model = genai.GenerativeModel('models/gemini-pro')

response = model.generate_content('generate a long story, more than 200 words, multiple graphs with breakline', stream=True)


for chunk in response:
    print(chunk.text)
```

**Comment by MarkDaoust** [comment]
@sykp241095 thanks for reporting. 

This is a limitation of Colab, long story. Try anywhere except Colab and you should get the chunks back as they are generated. LMK.
