### ISSUE TITLE
A plain text version of gemini 1.5

### ISSUE THREAD

**Issue by JaheimLee** [google-gemini/generative-ai-python#331]
It would be great if you can provide a text only Gemini 1.5 pro model and make QPS the same as Gemini 1.0 pro.

**Comment by singhniraj08** [comment]
@JaheimLee, Thank you reporting this issue. 
This repository is for issues related to Gemini Python SDK bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by MarkDaoust** [comment]
The new 1.5-flash model (announced at I/O today) should be significantly faster than 1.5-pro.
