### ISSUE TITLE
glm.FileData issue? with uris 

### ISSUE THREAD

**Issue by stephaniegoldman12** [google-gemini/generative-ai-python#357]
### Description of the bug:

google.api_core.exceptions.InvalidArgument: 400 Invalid or unsupported file uri: 

glm.FileData with a uri doesn't seem to work? I need to use Part.from_uri from the old vertex.preview library, but that library does not let me use `model = genai.GenerativeModel('gemini-1.5-pro-latest')`

### Actual vs expected behavior:

api_key = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-1.5-pro-latest')
response = model.generate_content(
    glm.Content(
        parts = [
            glm.Part(text="What is this image of?"),
            glm.Part(
                file_data=glm.FileData(
                    mime_type='image/png',
                    file_uri="gs://urihere.png"
                )
            ),
        ],
    ),
    stream=False)

print(response)

I'd expect this to work...but it says unsupported file uri (note: the uri is correct i just put a placeholder here for the example)

**Comment by zadiaz** [comment]
same here
<img width="709" alt="Screenshot 2024-05-24 at 11 29 39 AM" src="https://github.com/google-gemini/generative-ai-python/assets/23648790/a6542f8c-9ec6-42a9-85d3-7f2d22dc8395">

**Comment by VA-mzaki** [comment]
@zadiaz i think the only supported URI is the URIs from google file manager that start with https://generativelanguage.googleapis.com/v1beta/files

**Comment by MarkDaoust** [comment]
@va-mzaki  yes. This only supports files in the API. There are currently no plans to expand this. The Vertex's Gemini API handles some other FIleURIs.

**Comment by ben-xD** [comment]
This should be documented. I've used other generative AI services that do allow me to provide S3 presigned URLs, supabase storage URLs or even random image URLs. 

Basically I have to upload my files to Google's AI file manager?
