### ISSUE TITLE
Unclear finish_reason

### ISSUE THREAD

**Issue by akshit0201** [google-gemini/generative-ai-python#363]
### Description of the bug:

I'm just asking to summarize a high school textbook which I'm feeding as images, was working perfectly fine on Friday, getting the following error today:
```
GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({
      "candidates": [
        {
          "finish_reason": 4,
          "index": 0,
          "safety_ratings": [],
          "token_count": 0,
          "grounding_attributions": []
        }
      ]
    }),
)
```

I don't understand what finish_reason `4` means, it's not given here: [https://ai.google.dev/api/rest/v1/GenerateContentResponse](https://ai.google.dev/api/rest/v1/GenerateContentResponse)

### Actual vs expected behavior:

Actual: `"finish_reason": 4`

Expected: `"finish_reason": [Should be one of [https://ai.google.dev/api/rest/v1/GenerateContentResponse#finishreason](https://ai.google.dev/api/rest/v1/GenerateContentResponse#finishreason)]

### Any other information you'd like to share?

SDK version: 0.5.4

**Comment by singhniraj08** [comment]
@akshit0201, Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Python SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by Filimoa** [comment]
Can we please add better visibility into the finish reason? I get errors like

```
1
{'_pb': finish_reason: OTHER
index: 0
safety_ratings {
  category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HATE_SPEECH
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HARASSMENT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_DANGEROUS_CONTENT
  probability: NEGLIGIBLE
}
}
```

This makes gemini unusable in production when calls will randomly fail and you have no visibility into why?
