### ISSUE TITLE
Tuned models return no content!

### ISSUE THREAD

**Issue by maelghrib** [google-gemini/generative-ai-python#370]
### Description of the bug:

So I tuned the model using Python and it worked and completed as shown in the platform without any errors but when I tried using it in the studio it returned "No content" and when testing it with Python

Here is the code:
```
import google.generativeai as genai

generation_config = {
    "temperature": 0,
    "top_p": 1,
    "top_k": 1,
    "max_output_tokens": 400,
}

safety_settings = [
    {
        "category": "HARM_CATEGORY_HARASSMENT",
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_HATE_SPEECH",
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_NONE"
    },
]

name = "my-tuned-model"
model = genai.GenerativeModel(
    model_name=f"tunedModels/{name}",
    generation_config=generation_config,
    safety_settings=safety_settings
)

prompt_parts = [
    "input: my input here",
    "output: ",
]

response = model.generate_content(prompt_parts)
print(response)

```

and here is the response:
```
response:
GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({
      "candidates": []
    }),
)
```

**Comment by singhniraj08** [comment]
@maelghrib, Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Python SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by maelghrib** [comment]
Hi @singhniraj08 Okay I posted in the forum and sent a feedback, Thanks
