### ISSUE TITLE
Finish reason should be text not a number

### ISSUE THREAD

**Issue by logankilpatrick** [google-gemini/generative-ai-python#371]
### Description of the feature request:

See details reported by the user here: https://discuss.ai.google.dev/t/how-to-translate-finish-reason-4-from-generatecontentresponse-into-something-meaningful/4261

### What problem are you trying to solve with this feature?

Making the response object more clear, I checked REST and it responds with the text not a number

**Comment by mayureshagashe2105** [comment]
#340
