### ISSUE TITLE
The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

### ISSUE THREAD

**Issue by 141forever** [google-gemini/generative-ai-python#373]
### Description of the bug:

The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

### Actual vs expected behavior:

Traceback (most recent call last):
  File "D:\Study\codes\Gemini_score.py", line 64, in <module>
    strr = str(id) + ":" + response.text
  File "D:\Study\codes\venv\lib\site-packages\google\generativeai\types\generation_types.py", line 401, in text
    raise ValueError(
ValueError: The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

### Any other information you'd like to share?

THIS IS MY CODES:

import pandas as pd
import pdb
import google.generativeai as genai
import os

genai.configure(api_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

model = genai.GenerativeModel('gemini-1.5-pro')

response = model.generate_content(system_prompt)
strr = str(id) + ":" + response.text

system_prompt is a string

**Comment by singhniraj08** [comment]
@141forever, Similar feature request #282 is already filled. Requesting you to please follow and +1 the similar issue for updates and close this thread. Thank you!

**Comment by trunglebka** [comment]
@singhniraj08 I'm facing similar as the OP, since the `finish_reason` is always `OTHER` and the issue you linked is talking about safety I'm not sure it is related problem.
My prompt is as simple as translating a JSON object with the content "Hi Peter, how's it going?" along with related metadata like random bson ObjectId. Using the same prompt, I can easily get the result from ChatGPT, but Gemini (both Pro and Flash) just responds with `finish_reason=OTHER` so I don't even know what the problem is with the prompt.

**Comment by trunglebka** [comment]
Additional information:
With the same prompt I always get the expected result via the public gemini website https://gemini.google.com
With https://aistudio.google.com/app/prompts/new_chat , it is failed every time.
I can share the prompt via email if you guys are interested

**Comment by singhniraj08** [comment]
@trunglebka, #282 is for implementation of more helpful error messages when the response is blocked by Gemini because of safety or other reasons. The SDK doesn't control the service's responses. If you feel the response is blocked which shouldn't be the normal case, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).
![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by trunglebka** [comment]
@singhniraj08 Thanks for pointing that out, I wasn't paying close attention

**Comment by baptvit** [comment]
Im having the same issue, Im doing some rewriting text about healthcare [USML](https://paperswithcode.com/dataset/medqa-usmle) dataset. And in a specific question I got this error.

**Comment by architectyou** [comment]
@baptvit @141forever 

set the safety_settings and generate the content.
[https://ai.google.dev/gemini-api/docs/safety-settings?hl=en](https://ai.google.dev/gemini-api/docs/safety-settings?hl=en)

**Comment by baptvit** [comment]
@architectyou yeah, Ive tried to set the safety_settings

```python
response = GEMINI_MODEL.generate_content(prompt, safety_settings=[
    {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
    {"category": "OTHER", "threshold": "BLOCK_NONE"}
])
response.text
```

But even though I set up, I had to catch the exception:

```python
def rewrite_sentence(sentence_original, model=GEMINI_MODEL, template_prompt=TEMPLATE_PROMPT):
    try:
        prompt= template_prompt.replace("<original_sentence>", sentence_original)
        response = model.generate_content(prompt, safety_settings=[
    {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"}
])
        return response.text
    except Exception as e:
        return "Error text"
```

**Comment by phil-scholarcy** [comment]
Same error here, the safety settings have no effect on this particular issue

**Comment by ajitesh123** [comment]
Facing same issue for reviewing code (which is supposed to be written badly): The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

**Comment by Sumeet213** [comment]
> Facing same issue for reviewing code (which is supposed to be written badly): The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

Facing same issue as well

**Comment by brunoedcf** [comment]
Facing the same issue here

**Comment by ynie** [comment]
I'm still seeing the issue. Does google even care?

**Comment by ajitesh123** [comment]
You need to pass Safety Settings. Here is how I did in one of my open source repo: https://github.com/ajitesh123/auto-review-ai/blob/main/backend/llm.py#L177-L198

(Please star my repo if this solves for you :))

**Comment by phil-scholarcy** [comment]
> You need to pass Safety Settings. Here is how I did in one of my open source repo: https://github.com/ajitesh123/auto-review-ai/blob/main/backend/llm.py#L177-L198
> 
> (Please star my repo if this solves for you :))

Sadly changing the  safety sessions has no effect on this issue

**Comment by OGsiji** [comment]
Same error here too

**Comment by shilpakancharla** [comment]
@phil-scholarcy @OGsiji I can look into this issue for you. Can you please post a minimal working code sample here that caused this error for you? I tried OP's original code sample and I am unable to hit that error.

**Comment by hussainbiedouh** [comment]
Same now for Gemini 2.5. and Safety Settings have no effect.

**Comment by NurzihanReya** [comment]
Facing the same issue still
