### ISSUE TITLE
Unable to intercept requests to generativelanguages.google

### ISSUE THREAD

**Issue by JeevansSP** [google-gemini/generative-ai-python#385]
So I'm using a MITM proxy and when I run hit the API endpoint using requests python library, I'm successfully able to see the network trace in my middle man proxy log, but when I use this python package for the same task I'm unable to see the network trace to the generativelanguage.googleapis endpoint.

**Comment by MarkDaoust** [comment]
Hi, this library uses GRPC by default. You can switch it to use  rest with:

`genai.configure(transport="rest")`

Does that fix it for you?

**Comment by JeevansSP** [comment]
Hi @MarkDaoust, iIwent through the transport param and you're right if I give it a value of `rest` it needs to use the rest protocol for the Gemini service, but I'm still unable to see any traces in my MITM network calls when I use that param. I will check if there is anything else wrong and get back
