### ISSUE TITLE
response_schema not working with gemini-1.5-pro model

### ISSUE THREAD

**Issue by kunalhexus** [google-gemini/generative-ai-python#392]
### Description of the bug:

I ended up wasting 2 hours on trying to get it to work after seeing the official documentation for `contstrained generation` on https://ai.google.dev/gemini-api/docs/api-overview#json

Thanks for the pro tip of adding the schema to system prompt mentioned on #343 I was finally able to get it working.

The code generated on https://aistudio.google.com/ is also exteremly deceptive as it makes you input the schema making you believe that constrained generation is working and gives back the code which has no reference to JSON schema specified in Advanced Settings

### Actual vs expected behavior:

`response_schema` in model configuration should be respected without having to explcitly add the whole schema to system prompt

**Comment by singhniraj08** [comment]
@kunalhexus, I can see response_schema working with python sdk 0.5.4. 
Ref: screenshot below.
Can you please share a reproducible code to replicate the error on our end. Thank you!

![image](https://github.com/google-gemini/generative-ai-python/assets/110809167/20f21ffc-571c-4480-abcf-4df2eee9f6c6)

**Comment by AshishAcharya083** [comment]
Same issue: I've provided schema below. I've asked to 'reply in object with title and description' in pompt. But the model is completely ignoring the 'weekday' field. 

`export default class JsonSchema {
    static workoutRoutineSchema = {
        type: SchemaType.ARRAY,
        description: "List of objects with title and description",
        items: {
            type: SchemaType.OBJECT,
            properties: {
                title: {
                    type: SchemaType.STRING,
                    description:
                        "Title ending with suitable emoji (emoji as suffix) if available. Do not repeat emoji if it's already in previous title.",
                },
                description: {
                    type: SchemaType.STRING,
                    description: "The description of the item",
                },
                 weekday: {
                    type: SchemaType.STRING,
                    description: "week day name of week",
                },
            },
            required: ["title", "description"],
        },
    };
}
`
