### ISSUE TITLE
_OPERATOR dict with multiple 6 mentioned multiple times

### ISSUE THREAD

**Issue by PandasPirate** [google-gemini/generative-ai-python#411]
### Description of the bug:

just doing a static analysis of the code and found. I don't know how to fix it, so I am raising this issue.    

https://github.com/google-gemini/generative-ai-python/blob/630318b34f91c0d75b1a73131951a56c680005f3/google/generativeai/types/retriever_types.py#L109

**Comment by MarkDaoust** [comment]
Oh!

Thanks for pointing this out. Here's a correction: https://github.com/google-gemini/generative-ai-python/pull/419
