### ISSUE TITLE
Error when attempting to use Gemini 1.5 Pro: google.api_core.exceptions.InternalServerError: 500 An internal error has occurred

### ISSUE THREAD

**Issue by xarical** [google-gemini/generative-ai-python#468]
### Description of the bug:
Error when attempting to use Gemini 1.5 Pro: google.api_core.exceptions.InternalServerError: 500 An internal error has occurred

Error: 
![image](https://github.com/user-attachments/assets/ac489a62-191e-4730-a815-ac0bdbaf9663)

Changing this 
model = genai.GenerativeModel(model_name="gemini-1.5-pro",
                                generation_config=generation_config,
                                safety_settings=safety_settings)
to this
model = genai.GenerativeModel(model_name="gemini-1.5-flash-latest",
                                generation_config=generation_config,
                                safety_settings=safety_settings)
or this
model = genai.GenerativeModel(model_name="gemini-1.0-pro",
                                generation_config=generation_config,
                                safety_settings=safety_settings)
 "fixes" the issue. 

 
 The "fix" seems to suggest this a rate limit? But if it is a rate limit, the error message is very confusing (at first i thought "oh maybe if i just wait and try again later it'll work" and when that didn't happen it took me a LONG time to figure out what was causing it). Also, I understand 1.5 pro has a rate limit of 2 messages/minute, but I only sent one... 

### Actual vs expected behavior:

Expected: no error
Actual: error (screenshot in description)

### Any other information you'd like to share?

I tested this by switching the model to 1.5 pro on a couple of my other projects that use 1.5 flash. they give the same error after 1 and sometimes even 0 messages. Also yes I waited a couple minute in between tests

(note: generation_config and safety_settings from the code provided are defined elsewhere in my script along with response = model.generate_content(prompt))

**Comment by justarmadillo** [comment]
same issue

**Comment by E-sion** [comment]
same ....

**Comment by singhniraj08** [comment]
@xarical,
Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Python SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Google AI forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
