### ISSUE TITLE
Get finish_reason: 6 without reason and content reply

### ISSUE THREAD

**Issue by A-baoYang** [google-gemini/generative-ai-python#476]
### Description of the bug:

When sending some specific conversations to `gemini-1.5-flash` will get finish_reason: 6, and this finish_reason can't be found in official document:
![image](https://github.com/user-attachments/assets/c903dd8d-178b-46d0-aa66-948a575aeea6)

Why is this cause?

#### Environment details

  - OS type and version: Ubuntu
  - Python version: 3.11.9
  - pip version: 24.0
  - package versions:
google-ai-generativelanguage            0.6.6                                                                  
google-api-core                         2.19.1                                                                 
google-api-python-client                2.137.0                                                                
google-auth                             2.32.0                                                                 
google-auth-httplib2                    0.2.0                                                                  
google-generativeai                     0.7.2

#### Code example

```python
GEMINI_MODEL = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0,
)
prompt = ChatPromptTemplate.from_template(prompt_tmpl)
chain = prompt | GEMINI_MODEL | StrOutputParser()
response = chain.invoke(prompt_parmas)
```

#### Error trace
```
[2024-07-19 10:51:30,697] [langchain_google_genai.chat_models | line:561 | _response_to_result] [ERROR] - response: candidates {
  index: 0
  finish_reason: 6
}
usage_metadata {
  prompt_token_count: 1961
  total_token_count: 1961
}
```

**Comment by singhniraj08** [comment]
@MarkDaoust, I can't see `finish_reason: 6` in [google.generativeai.protos.Candidate.FinishReason](https://github.com/google-gemini/generative-ai-python/blob/main/docs/api/google/generativeai/protos/Candidate/FinishReason.md). Do we need to update the documentation to include finish_reason:6? Thank you!

**Comment by MarkDaoust** [comment]
Hi, thanks for pointing this out.

It turns out the API added "LANGUAGE" as a stop reason. Ask a question in Esperanto (for example) to trigger it:

```
response = m.generate_content('Saluton kiel vi fartas hodiaŭ? Mi havas kelkajn demandojn pri bestoj. Ĉu ornitorinkoj vere estas mamuloj?')
response.candidates[0]
# index:0  finish_reason: 6
```

So I need to update the generated client library `google.ai.generativelanguage` to fix this.

**Comment by MarkDaoust** [comment]
I got the ball rolling on a new version of google.ai.generativelanguage, that should fix this.

**Comment by MarkDaoust** [comment]
Oh, the API has turned off language filtering. 
Try again. That Esperanto example of mine goes through now. 
Maybe we'll never see a 6 again.
