### ISSUE TITLE
Ag2279122/Workday
www.githubstatus.com/?subscription_confirmed=Trustee

### ISSUE THREAD

**Issue by Ag2279122** [google-gemini/generative-ai-python#477]
"Google Flights - Find Cheap Flight Options & Track Prices" https://www.google.com/travel/flights?safe=on&client=mobile-google-go-organic&sca_esv=33f171317715abb5&sca_upv=1&hl=en&output=search&q=ag22+72yaZuvYD_vIkPIP77mggAM&source=lnms&fbs=AEQNm0A633aOWMcGwo5EkodWqZWQOBeVdwv8ew4rvBGv_27VjctEZwTrWDTasJgLpO3Kgjol8-8yqzOOSvV7PKqg2zM6ko0mnZXnKr4mCwH-RUgo2T_j0stKm5g5kfLJGMr5WpnJNFoxGeELTHQ74eTDBFNGoieVuCnNK4zpHNIB5oV_owWCDTLitlfDWLxxqU7FhDrVT_2T0lA6VpH2f807_BOeUSJIdA&ved=1t:200715&ictx=111github.com/google-gemini/generative-ai-python/issues/477/Workday

**Comment by PandasPirate** [comment]
Please share more details on the issue with current and expected behaviour or the error message.

**Comment by singhniraj08** [comment]
@Ag2279122,
We see that the issue [template](https://github.com/google-gemini/generative-ai-python/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [SDK version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced and reopen this issue. Thanks!
