### ISSUE TITLE
7314874656

### ISSUE THREAD

**Issue by Ag2279122** [google-gemini/generative-ai-python#479]
files []() to unistall @ftnext @YebowenHu @markmcd @dmotz @philippemiron @mgechev @dmotz @yaoshengzhe @mgechev - [ ] - @random-forests []()@nbro @Andy963 @thatfiredev @luo-anthony @yihong0618 @eavanvalkenburg @aertoria @mpursley @rozha @waltforme @elsiel23 @mbanani

**Comment by PandasPirate** [comment]
Please share more details on the issue with current and expected behaviour or the error message.

**Comment by singhniraj08** [comment]
@Ag2279122, 
We see that the issue [template](https://github.com/google-gemini/generative-ai-python/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [SDK version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced and reopen this issue. Thanks!
