### ISSUE TITLE
google.generativeai.chat does not support max_output_tokens

### ISSUE THREAD

**Issue by chrbsg** [google-gemini/generative-ai-python#48]
We want to limit the reply length of chat responses, but [google.generativeai.chat](https://developers.generativeai.google/api/python/google/generativeai/chat) does not appear to support the `max_output_tokens` parameter. I'm not sure whether this is just not implemented yet, or an API limitation, or something else, but the vertexai Python SDK Chat model appears to support it (see [Vertex AI Chat model parameters](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models#chat_model_parameters)) and so does the [google.generativeai.generate_text function](https://developers.generativeai.google/api/python/google/generativeai/generate_text). 

I had thought that perhaps `max_output_tokens` wasn't supported in chat, just text generation, but [this doc](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/intro_palm_api.ipynb) clearly shows it being used in a chat:

```
chat = chat_model.start_chat(
    context="My name is Ned. You are my personal assistant. My favorite movies are Lord of the Rings and Hobbit.",
    examples=[
        InputOutputTextPair(
            input_text="Who do you work for?",
            output_text="I work for Ned.",
        ),
        InputOutputTextPair(
            input_text="What do I like?",
            output_text="Ned likes watching movies.",
        ),
    ],
    temperature=0.3,
    max_output_tokens=200,
    top_p=0.8,
    top_k=40,
)
print(chat.send_message("Are my favorite movies based on a book series?"))
```

(It's a bit confusing that Google seems to have two different Python SDKs, this google-generativeai one and google-cloud-aiplatform. Is there any difference if all a developer wants to do is send chat to a model and get responses back?)

**Comment by liamdugan** [comment]
+1 to this, also having this issue

**Comment by ryuryukke** [comment]
I found that a PaLM Chat model in Vertex AI SDK supports max_output_tokens.: https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-chat

**Comment by MarkDaoust** [comment]
The palm based interface is no longer a priority. Closing.
