### ISSUE TITLE
Context Cache and updating Gemini Code Assist

### ISSUE THREAD

**Issue by gaoptimize** [google-gemini/generative-ai-python#485]
### Description of the feature request:

First, Thanks for making this easy to use library for those of us with limited Python skills.  I spent a number of fruitless hours trying to create a context cache because Gemini Code Assist (the star on the left sidebar of VSC) thought that google.generativeai had a Content class that has a Cache class, importing it and trying to use it with no success.  Apparently it was confused with Vertexai, a heavier library that requires one to have a Google Project and a "GOOGLE_API_KEY" when all I have is a "GEMINI_API_KEY".  Could you please consider adding a context cache to this library and convince Google to update their Code Assist to your 0.2.7 (?) version?  $50 tip to whoever does this in the next 2 months.  I needed it last week.

### What problem are you trying to solve with this feature?

I'm sending and sharing large text files between AIs.  A cache would eliminate some repetitive network traffic and latency.

### Any other information you'd like to share?

Worse comes to worst, I'll learn Vertexai, but it seems confusing.

**Comment by MarkDaoust** [comment]
Hi, 

We do have caching support, see the example here:

https://github.com/google-gemini/cookbook/blob/main/quickstarts/Caching.ipynb

And the docs here:

https://ai.google.dev/gemini-api/docs/caching?lang=python

Have fun!

**Comment by abrahmecha** [comment]
I am using context caching for gemini-1.5-flash-001 with 39k input tokens as cached tokens .. before caching the response time was 7 seconds on avg but after caching it is almost more than doubled. Time to create cache for 39k tokens - 18s avg and time for response - 20 seconds on avg which is almost thrice. Is it something like 39k tokens are less to be cached or what can be the reason ? Also prompt consist of normal text and image urls and image descrpition and usecase is to analyse the images of food and provide food name and food quantity. As of now I have cached 113 Images. (113x258 + 4000 system prompt + 6000 food image description )
Reaching out for help !

**Comment by MarkDaoust** [comment]
Hi, 

Caching lowers the **cost** per request, we don't make any claims that it speeds up requests.

We hope to that we will be able to eventually, but it doesn't yet.

**Comment by gaoptimize** [comment]
Hi,

   I'll be passing ~10k token document sections, comments, and drafts between 3 to 5 LLMs.  I'm pretty sure it will not only be costly and slow, it will clog up the contexts with redundant and incorrect information.  I need direct control over the cache, not just dumping it every cycle.

   Imagine people in a meeting taking a bathroom break and when they get back, everyone has forgotten everything that had been said before.  LOL.

-Tom
________________________________
