### ISSUE TITLE
Latest Python does not supported

### ISSUE THREAD

**Issue by safwaahmad** [google-gemini/generative-ai-python#503]
### Description of the feature request:

Latest Python does not supported the streamlit for deployment

**Comment by singhniraj08** [comment]
@safwaahmad,
We see that the issue [template](https://github.com/google-gemini/generative-ai-python/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [SDK version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced and reopen this issue. Thanks!
