### ISSUE TITLE
Tuned model creation failed

### ISSUE THREAD

**Issue by chalitbkb** [google-gemini/generative-ai-python#508]
### Description of the bug:

I have a question. Why do I encounter the issues shown in the attached image when I import data directly through the website?

Or is it about the language? I tried using English, and it works just fine. But when it's another language, it can't proceed. So I want to know if this issue is related to the language. If so, what languages does the training data support, or is it only English?

![image](https://github.com/user-attachments/assets/a854488b-76c1-402f-8057-c6bcf2a76609)

**Comment by OumarDicko** [comment]
Hi I have the same problem when i try to use another language, maybe it that

**Comment by gmKeshari** [comment]
@chalitbkb 

Thank you reporting this issue. This repository is for issues related to Python SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to AI Studio, we would suggest you to use "Send Feedback" option in AI Studio. Ref: Screenshot below. You can also post this issue on [Google AI forum](https://discuss.ai.google.dev/).

![image](https://github.com/user-attachments/assets/ffd792b5-b6c3-4d98-85eb-ac05153fa7e8)

**Comment by likawa3b** [comment]
I have the same problem as well.
![image](https://github.com/user-attachments/assets/a7a9710b-1b04-4de9-9b5a-95bd7da31667)

**Comment by MarkDaoust** [comment]
Interesting. It's too bad there isn't a clearer error there.

If it was the language causing the problem, IIUC:

1. The API recently relaxed language support. 
2. It added "LANGUAGE" to the enum for "finish_reason". Have you tried a "generate_content" request in that language? does it work?
