### ISSUE TITLE
AttributeError: partially initialized module 'google.generativeai' has no attribute 'configure' (most likely due to a circular import)

### ISSUE THREAD

**Issue by sankydesai** [google-gemini/generative-ai-python#525]
### Description of the bug:

I don't know why this is happening.

import google.generativeai as gai
import os
gai.configure(api_key=os.getenv('GEMINI_API_KEY'))

model = gai.GenerativeModel('gemini-pro')

prompt = "Write a story about a magic backpack."
response = model.generate_content(prompt)

print(response.text)

Also ran it in a new environment with no similar named libraries.

### Actual vs expected behavior:

Work correctly?

**Comment by manojssmk** [comment]
Hi @sankydesai 

The error you are encountering is likely due to having a file named generativeai in your local drive or saving your Python file as generativeai.py.

Thanks

**Comment by MarkDaoust** [comment]
+1 there's not a lot we can do here without a little more information. What environment does your setup use? How are you installing it? Can you, for example, reproduce this in Colab?

**Comment by sankydesai** [comment]
so there was a problem with my system. closing this now. It works on colab. Thanks guys
