### ISSUE TITLE
Deadline Exceeded Error in DocumentServiceClient with updateDocument in discoveringengine

### ISSUE THREAD

**Issue by Sami-80** [google-gemini/generative-ai-python#534]
### Description of the feature request:

I am encountering a DEADLINE_EXCEEDED error while using the updateDocument method in the DocumentServiceClient of the discoveringengine service. This issue is preventing me from updating documents within the Discovery Engine in a timely manner, impacting the overall functionality of my application.

export async function createDoc(body: any) {
  await docService.updateDocument(
    {
      allowMissing: true,
      document: {
        name: `project`,
        jsonData: JSON.stringify(body),
      },
    },
  );
  }

**Comment by manojssmk** [comment]
Hi @Sami-80 

Could you please elaborate on the issue that you are facing and please let us know how this is related to Gemini API.

Thanks
