### ISSUE TITLE
Upload file via stream

### ISSUE THREAD

**Issue by LindaLawton** [google-gemini/generative-ai-python#537]
### Description of the feature request:

Currently the only way to upload a file is to send the path of the file

It looks like [client.py#L73](https://github.com/google-gemini/generative-ai-python/blob/e0928fc0f239242f0cf5d69b6821188a8dac4e66/google/generativeai/client.py#L73)

Is there anyway to get this to take a stream

    media = googleapiclient.http.MediaFileUpload(
            filename=path, mimetype=mime_type, resumable=resumable
        )

### What problem are you trying to solve with this feature?

I am downloading a file from another site and would rather not have to save it to disk only to send it to Gemini.

### Any other information you'd like to share?

please

**Comment by Hamza-nabil** [comment]
Yes, you can use the [MediaIoBaseUpload](https://github.com/googleapis/google-api-python-client/blob/291d13c0287f95a686f5a90935e92849e5899043/googleapiclient/http.py#L428)  class to upload a stream instead of a file path. 

```python
fh = BytesIO('...Some data to upload...')

media = googleapiclient.http.MediaIoBaseUpload(
     fh, mimetype=mime_type, resumable=resumable
)
```

**Comment by MarkDaoust** [comment]
Oh nice, thanks for the tip @Hamza-nabil. We should do this.

**Comment by Hamza-nabil** [comment]
I have created a draft PR #556 to add support for streaming file uploads in the `upload_file` function. 

@MarkDaoust Can you please review it and provide feedback ?

### Next Steps:

- [ ] **Argument Name Change:** Renaming the `path` argument to something more descriptive like `file_source`. This change is not a priority as it may impact existing code.

- [ ] **Update Tests:** Add test cases specifically for file stream scenarios.


Any additional improvements or steps needed for this feature?


Thank you!

**Comment by MarkDaoust** [comment]
Fixed by: https://github.com/google-gemini/generative-ai-python/pull/556

> Update Tests: Add test cases specifically for file stream scenarios.

I included one in the PR.

>  Argument Name Change: Renaming the path argument to something more descriptive like file_source. This change is not a priority as it may impact existing code.

Yeah, backwards compatibility is always important.

**Comment by ruanyanghui** [comment]
The sample_audio = genai.upload_file(pic/ "img2.png") line uses the Python SDK's built-in upload functionality. Is there an equivalent way to achieve this file upload using an HTTPS request directly, without relying on the SDK?
