### ISSUE TITLE
protobuf dep is < 5.0

### ISSUE THREAD

**Issue by abaoai** [google-gemini/generative-ai-python#539]
### Description of the bug:

The 4.xx protobuf packages are outdated.

**Comment by Gunand3043** [comment]
@abaoai , Could you please provide more details about the issues you're facing?

Are there any particular features or functionalities that are not working as expected?

**Comment by abaoai** [comment]
I have downstream service built with grpc as well. The generated python code runs on the latest 5.27. It breaks when running on the latest protobuf(5.28). So I have to pick 5.27 in requirements.txt. That triggers a docker build error when both protobuf 5.27 and generative-ai-python lives in the same requirements.txt file.

**Comment by MarkDaoust** [comment]
I pushed a v0.8.0 release this morning: https://pypi.org/project/google-generativeai/#history

Installing that gets a >5.0.0 version of protobuf.

Fixed.
