### ISSUE TITLE
Cannot parse value of 'http_proxy' env var

### ISSUE THREAD

**Issue by dengwen168** [google-gemini/generative-ai-python#584]
### Description of the bug:

I test the python code and got the following error msg,
How to solve this issue? thanks.
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1728007314.658664     284 http_proxy_mapper.cc:130] cannot parse value of 'http_proxy' env var. Error: INVALID_ARGUMENT: Could not parse 'scheme' from uri '127.0.0.1:7890'. Scheme must begin with an alpha character [A-Za-z].

**Comment by manojssmk** [comment]
Hi @dengwen168 

Please share the sample code and prompt you are using so it can be debugged. Have you tried running the same code in Colab?

Thanks
