### ISSUE TITLE
Quickstart script is not working as expected

### ISSUE THREAD

**Issue by codewithnick** [google-gemini/generative-ai-python#604]
### Description of the bug:

I am following the quickstart script to generate content
```
import os
import google.generativeai as genai
import dotenv
dotenv.load_dotenv()
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
#print(GEMINI_API_KEY)
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content("Write a story about a magic backpack.")
print(response.text)
```

### Actual vs expected behavior:

Actual behaviour :
<img width="379" alt="image" src="https://github.com/user-attachments/assets/aff04135-b251-4aa3-adf5-34a0b6b338ca">
nothing is being printed, no error nothing, gemini has got stuck i have no idea how to debug this

Expected behavior:
response must be printed

### Any other information you'd like to share?

GEMINI_API_KEY is corrrect and new , even tried printing it and it prints correctly
python version: 3.12.6
OS: mac

**Comment by manojssmk** [comment]
Hi @codewithnick 

I ran the same code with the same versions in VS Code, and it worked fine. The output may take time since there's an API call involved. Have you tried running it in Google Colab? 

Thanks

**Comment by codewithnick** [comment]
I tried making a postman request with the same api key and it worked,probably something is wrong with the python module , the biggest problem is i don't know how to debug this ,there is no response no error at all it just gets stuck.

**Comment by codewithnick** [comment]
tried that, same problem

**Comment by codewithnick** [comment]
ok i fixed that after some trail and error , looks like my venv and python version were different i reinstalled and resetup everything
