### ISSUE TITLE
GenerationConfig Error: 'seed' Field Missing in Protocol Message but Present in GenerationConfig Class

### ISSUE THREAD

**Issue by emersoftware** [google-gemini/generative-ai-python#605]
### Description of the feature request:

I'm trying to set the seed for Gemini using the 'google-generativeai' library:

```
model = genai.GenerativeModel(
    model_name,
    system_instruction=system_instruction,
    generation_config=GenerationConfig(
        temperature=0.0,
        seed=42
    )
)
```

However, I'm getting the following error:

`"ValueError: Protocol message GenerationConfig has no \"seed\" field."`

I understand that this happens because the `GenerationConfig(proto.Message) `class from `google.generativeai.types` doesn't have a seed attribute. However, this attribute does exist in the `GenerationConfig` class, which is accepted as a type in `GenerationConfigType = Union[protos.GenerationConfig, GenerationConfigDict, GenerationConfig]` from `google.generativeai.types.`

I believe this is an inconsistency

### What problem are you trying to solve with this feature?

I would like to set a seed value in the `GenerationConfig` when using the Gemini API to ensure reproducibility of the generated output. Since the seed attribute already exists in the `GenerationConfig` class, adding support for it in `protos.GenerationConfig` would provide a more consistent experience

**Comment by gmKeshari** [comment]
Hi @emersoftware.

Seed attribute is still not present in Gemini API SDK, but it is present in VertexAI SDK. The team is working to have this attribute in the Gemini API SDK as well.

We have a similar GitHub discussion. If you wanna refer please go through this [#536](https://github.com/google-gemini/generative-ai-python/issues/536)

**Comment by MarkDaoust** [comment]
Yeah, we thought this was going to make it into the last release of the API, and then it didn't. Let's remove it from the SDK until it's supported.

**Comment by MarkDaoust** [comment]
https://github.com/google-gemini/generative-ai-python/pull/609

**Comment by yzvickie-apple** [comment]
I'm can't set seed using vertexai:

```
model = vertexai.generative_models.GenerativeModel(
    "gemini-1.5-pro-001",
    generation_config=GenerationConfig(
        temperature=0.0,
        seed=42
    )
)
```

returns error  GenerationConfig.__init__() got an unexpected keyword argument 'seed'
