### ISSUE TITLE
ModuleNotFoundError: No module named 'google.generativeai'

### ISSUE THREAD

**Issue by DronePower69** [google-gemini/generative-ai-python#606]
### Description of the bug:

Using the following code:
`import os`
`import google.generativeai as genai`

I tried every method there was.

I even did: 
- pip install google-generativeai
- pip install -U google-generativeai
- pip install google-ai-generativelanguage

Please help me with this

### Actual vs expected behavior:

Working in colab, but giving the error ; "ModuleNotFoundError: No module named 'google.generativeai'"

### Any other information you'd like to share?

import os
import google.generativeai as genai

GOOGLE_API_KEY="---"
genai.configure(api_key=os.environ[GOOGLE_API_KEY]) 

prompt = input("You: ")

# Generate a response
model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content(prompt)
print(response.text)

**Comment by manojssmk** [comment]
Hi @DronePower69 

It worked fine when I tested it in Google Colab. You can check out the [gist here](https://colab.sandbox.google.com/gist/manojssmk/c8849b6035566e2fa2ff9944d7f7face/issue606.ipynb). Please try running the code from the provided link.

Thanks

**Comment by MarkDaoust** [comment]
`google` is a namespace package. They have some strange behaviors. 

- Have you tried uninstalling the package?
- Have you tried creating a fresh virtualenv?
- Are you sure your pip is installing into the same python environment that you're running?

**Comment by sukruburakcetin** [comment]
Considering you have a version of Python 3.8 or below, you need to use a version of Python 3.9 or higher. I had a problem with the 3.8 version. I've tested with Python 3.10.15, it works flawlessly.

**Comment by MarkDaoust** [comment]
@sukruburakcetin, yes, we don't support Python < 3.9. Please upgrade your python, I bet that will fix it.

**Comment by ghiahemanshu** [comment]
I was running into the same issue. I was on python 3.12. Downgrading to python 3.11 fixed it.
