### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Sajal-26** [google-gemini/generative-ai-python#607]
### Description of the bug:
module 'google.generativeai.protos' has no attribute 'DynamicRetrievalConfig'. Did you mean: 'SemanticRetrieverConfig'?

I'm getting this error in the import line

``` python
import google.generativeai as genai
```

**Comment by Gunand3043** [comment]
Hi @Sajal-26 , I tried with the above installation command you shared and it work. 

You might need to restart the session after installing.

**Comment by Sajal-26** [comment]
Thanks @Gunand3043 Now there's a different error!

raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.NotFound: 404 models/imagen-3.0-generate-001 is not found for API version v1beta, or is not supported for predict. Call ListModels to see the list of available models and their supported methods.

Maybe is it because it is not available with my API_Key?

**Comment by Hamza-nabil** [comment]
@Sajal-26 I think that why , see [Generate images using Imagen 3  ](https://ai.google.dev/gemini-api/docs/imagen)

> Preview: Imagen 3 in the Gemini API is available as an early access release in private preview. It's not yet generally available.
