### ISSUE TITLE
Make Tool and grounding available in StudioAI library as in VertexAI

### ISSUE THREAD

**Issue by souzatharsis** [google-gemini/generative-ai-python#618]
### Description of the feature request:

Support for Tool and grounding in `google.generativeai` as available in VertexAI: 

`from vertexai.generative_models import Tool, grounding`

### What problem are you trying to solve with this feature?

I would like to use grounding function as a tool from StudioAI library in generic LLM base, e.g. langchain.

In particular, be able to make the following call but using `google.generativeai` instead of `vertexai`

`Tool.from_google_search_retrieval(ground.GoogleSearchRetrieval())`, which today is possible in `vertexai.generative_models`

### Any other information you'd like to share?

Thanks for making grounding available.

**Comment by manojssmk** [comment]
Hi @souzatharsis 

Grounding is available in the Gemini API and AI studio. Refer to this documentation [link](https://ai.google.dev/gemini-api/docs/grounding?lang=python).

Thanks

**Comment by souzatharsis** [comment]
Hi, I understand grounding feature is available in Gemini high level api.

My request instead is lower level capability.

In particular, I'd like to be able to run the below code using studioai's
`google.generativeai` library instead of VertexAI:

from vertexai.generative_models import Tool, grounding

#and the be able to call

Tool.from_google_search_retrieval(ground.GoogleSearchRetrieval())

**Comment by souzatharsis** [comment]
Yes, thanks!

But using studioai's `google.generativeai` library instead of VertexAI
