### ISSUE TITLE
upload_file returns 0 byte file with no mime_type (high severity)

### ISSUE THREAD

**Issue by mikewadhera** [google-gemini/generative-ai-python#628]
### Description of the bug:

`genai.upload_file(path=path, mime_type=mime_type)`

Any code that was once working downstream of this, including `generate_content` now fails

Looks like this was from a production push? Started today 11/11/24 around noon PDT.

Also #627 likely related

### Actual vs expected behavior:

Expected: a file with proper `size_bytes` and `mime_type`

Actual: `size_bytes` always zero and `mime_type` always `''`

### Any other information you'd like to share?

Looks like this was from a production push? Started today 11/11/24 around noon PDT.

Also #627 likely related

**Comment by sahilshah** [comment]
We are seeing this as well (also Hi Mike!)

**Comment by nharada1** [comment]
Same issue here, even manually setting the mime_type doesn't do anything

**Comment by sahilshah** [comment]
Even the example notebooks on Gemini docs are broken
e.g. https://ai.google.dev/gemini-api/docs/vision?lang=python

**Comment by teyou** [comment]
same here.

**Comment by javivallejo** [comment]
Following up for visibility. I reached out on Twitter and got a response, so they should be aware.
https://x.com/OfficialLoganK/status/1856130496058495019

**Comment by adboio** [comment]
+1 seeing this as well

**Comment by adboio** [comment]
is this only happening with the python SDK? can we call the API directly as a temp fix here?

**Comment by sidpremkumar** [comment]
> is this only happening with the python SDK? can we call the API directly as a temp fix here?

failing with the node sdk as well @adboio

**Comment by adboio** [comment]
related post on google cloud forums: https://www.googlecloudcommunity.com/gc/AI-ML/Gemini-API-method-models-generateContent-returns-error-code-400/m-p/831749

**Comment by m-a-sch** [comment]
So happy to not just be the only one. Who changed the server side of file_upload?

**Comment by adboio** [comment]
found a potential workaround! :rocket: 

instead of calling `upload_file`, use the `Blob` type and pass file contents directly to the `generate_content`:

```
model = genai.GenerativeModel("gemini-1.5-pro")

with open(media_filepath, 'rb') as fp:
    file_contents = fp.read()
    media_blob = protos.Blob(data=file_contents, mime_type=mime_type)

    response = model.generate_content([media_blob, prompt_text],
        generation_config=genai.GenerationConfig(
            response_mime_type="application/json", response_schema=Recipe
        )
    )
```

**Comment by hosopy** [comment]
I'm having the same issue

**Comment by adboio** [comment]
my use-case is for video files, and the workaround i posted above does not work if the files are too large... i tried splitting the file into multiple parts and uploading the blobs individually (like `generate_content([ blob1, blob2, blob3, "prompt" ])`), but it seems the payload limit is on the entire payload, not individual parts... so i'm not sure of any workaround for larger files at this point

**Comment by m-a-sch** [comment]
My work around is to wait. Is this the first major outage of this beautiful product?

**Comment by adboio** [comment]
working for me now too!

**Comment by davaram** [comment]
It’s finally working again!

But, Why?

**Comment by logankilpatrick** [comment]
Hey! We rolled out a fix for this issue, apologies for the delay. I am going to also get a status page setup to make it easier to follow this stuff in the future.

**Comment by rnckp** [comment]
I still get the error. I am using the latest Python client. 

Uploading a PDF with 128 pages and a total file size of 161MB yields:

`InvalidArgument: 400 Request contains an invalid argument.`

How can I fix this?

**Comment by zlydenko** [comment]
Not working for me too, same error

**Comment by rshrc** [comment]
Same here! Exact same issue

**Comment by mike6789** [comment]
FIX THIS GOOGLE

**Comment by krishna-exe** [comment]
not working, fix it google
