### ISSUE TITLE
404 models/imagen-3.0-generate-001 is not found for API version v1beta

### ISSUE THREAD

**Issue by NavosX** [google-gemini/generative-ai-python#633]
### Description of the bug:

While running the code from the [Google Gemini API Docs](https://ai.google.dev/gemini-api/docs/imagen), the following error occurs:
`google.api_core.exceptions.NotFound: 404 models/imagen-3.0-generate-001 is not found for API version v1beta, or is not supported for predict. Call ListModels to see the list of available models and their supported methods.`

**Comment by Gunand3043** [comment]
@NavosX , Imagen-3 in the Gemini API is not publicly available yet.  

We already have an open GitHub issue for this, #597
