### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 The service is currently unavailable.

### ISSUE THREAD

**Issue by zijianh4** [google-gemini/generative-ai-python#64]
### Description of the bug:

I met the error message `google.api_core.exceptions.ServiceUnavailable: 503 The service is currently unavailable.` frequently. Especially when I try to call the API multiple times using a loop. Is this a bug or is there a way to solve it? Thanks!

### Actual vs expected behavior:

Should generate text or chat correctly but frequently have the error `google.api_core.exceptions.ServiceUnavailable: 503 The service is currently unavailable.`

**Comment by dinobby** [comment]
I am facing the same issue, and this did not happen a few days ago.

**Comment by ymodak** [comment]
Hi @zijianh4 and @dinobby, Can you please share more information such as python version, region? Also do you see 503 error if you make api call once instead of multiple calls via loop? Thank you.

**Comment by zijianh4** [comment]
> Hi @zijianh4 and @dinobby, Thanks for reporting. Can you please share more information such as python version, region? Also do you see 503 error if you make api call once instead of multiple calls via loop? Thank you.

Hi @ymodak ,
Sure. My Python version is 3.10.12 and region is US. I see 503 error when multiple calls via loop. I think it may be because the API is called too often so I tried to set some pause (~15s) between each call, but after some period it still shows the 503 error. Thanks.

**Comment by mindwellsolutions** [comment]
Update: Through out the day it was able to do something 10 queries before giving the 503 error, sometimes 70-200 queries before it would appear. All queries were administered exactly the same way between all these events. Now hours later its working perfectly again, I just processed 1,500 queries making sure to stay under the 90 responses per minute limits from PaLM and its working fine again.

This leads me to believe its a problem on Google's PaLM API Servers or maybe some aspect of the PaLM API codebase that connects to Google PaLM. 

Any help to get this resolved would be incredible. It's hard to build anything on the PaLM API knowing I might be getting the 503 error randomly throughout the day. Much thanks in advance.

**Comment by mindwellsolutions** [comment]
SOLUTION that detects 503 errors, waits 2 seconds and then retries the last PaLM API query. This completely fixed my issue with the 503 error.

`    while retry:
        try:
            completion = palm.generate_text(
            model=model,
            prompt=prompt1,
            temperature=0,
            # The maximum length of the response
            max_output_tokens=800,
        )
            retry = False
        except Exception as e:
            print(f"\033[1;31mAn exception occurred: {e}. Retrying in 2 seconds...\033[0m")
            time.sleep(2)`

**Comment by MarkDaoust** [comment]
Hi, in recent releases we've added automatic retry logic to the underlying client library.

Like here: https://github.com/googleapis/google-cloud-python/blob/bd35749e76375874667b324d4b558a9bddc554c1/packages/google-ai-generativelanguage/google/ai/generativelanguage_v1/services/generative_service/transports/base.py#L129-L143

It has a 60s timeout for most methods, 600s for generate_content.

So I believe this is fixed.
