### ISSUE TITLE
Unable to use safety settings in chat mode of chat bison

### ISSUE THREAD

**Issue by TheGodPancake** [google-gemini/generative-ai-python#81]
It would be nice to be able to configure the safety settings for chat bison. This would hopefully lessen getting "none" as a response. It would also help with making examples more reliable, and make chat mode able to register a name.

**Comment by markmcd** [comment]
Internal: b/296349374

**Comment by liamdugan** [comment]
+1 to this as well, am puzzled as to why we can set safety settings for text completions but not chat completions

**Comment by sr229** [comment]
Another +1 to this as well, it's hard to tailor Chat Bison for my specific needs if I cannot tweak the safety filtering for it.

**Comment by jmtb095** [comment]
+1

**Comment by MarkDaoust** [comment]
We've stopped development on the palm based interface. Closing.
