### ISSUE TITLE
How does google.generativeai.count_message_tokens work?

### ISSUE THREAD

**Issue by ryuryukke** [google-gemini/generative-ai-python#99]
Hi there, 
I tried to count the token number of a text using `google.generativeai.count_message_tokens` according to the following code.
I got 12 for the input "a".
Does `google.generativeai.count_message_tokens` include something besides a prompt, which is now "a" ?
I would appreciate any comments.

Thanks.

```Python
import google.generativeai as palm
import os
palm_api_key = os.getenv("PALM_API_KEY")

palm.configure(api_key=palm_api_key)

def count_tokens(string):
    res = palm.count_message_tokens(model='models/chat-bison-001', prompt=string)
    return res['token_count']

print(count_tokens('a'))
# 12
```

**Comment by huberemanuel** [comment]
It seems to be working fine with `gemini-pro`

**Comment by MarkDaoust** [comment]
`count_message_tokens` was a palm based interface. We've stopped development on those (use `GenerativeModel.count_tokens`). Closing.
